# Generated by Django 4.1.3 on 2023-06-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie_Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cookie', models.CharField(max_length=100)),
                ('User', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100, null=True)),
                ('Plans', models.CharField(max_length=100, null=True)),
                ('Verify', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Country', models.CharField(max_length=100, null=True)),
                ('Statuse', models.CharField(max_length=100, null=True)),
                ('Last_Seen', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
