# Generated by Django 4.1.3 on 2023-06-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0002_remove_signup_info_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_info',
            name='Full_Name',
            field=models.CharField(max_length=100),
        ),
    ]
